/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ContenidoVisual;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author JORGE BURBANO
 */
public class Ganaste extends javax.swing.JFrame {

     ImageIcon imagen;
    Icon icono;
    public Ganaste() {
        initComponents();
         setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/iconojuego.png")).getImage());
        setResizable(false);
        ponerImagenesIconos(btn_icono_ganador);
        ponerImagenesIconos(btn_icono_ganador2);
        ponerImagenesIconos(btn_icono_ganador3);
        ponerImagenesIconos(btn_icono_ganador4);
        ponerImagenesIconos(btn_icono_ganador5);
        ponerImagenesIconos(btn_icono_ganador6);
        ponerImagenesIconos(btn_icono_ganador7);
        ponerImagenesIconos(btn_icono_ganador8);
        ponerImagenesIconos(btn_icono_ganador9);
        ponerImagenesIconos(btn_icono_ganador10);
        ponerImagenesIconos(btn_icono_ganador11);
        ponerImagenesIconos(btn_icono_ganador12);
        ponerImagenesIconos(btn_icono_ganador13);
        ponerImagenesIconos(btn_icono_ganador14);
        ponerImagenesIconos(btn_icono_ganador15);
        ponerImagenesIconos(btn_icono_ganador16);
        ponerImagenesIconos(btn_icono_ganador17);
        ponerImagenesIconos(btn_icono_ganador18);
        ponerImagenesIconos(btn_icono_ganador19);
        ponerImagenesIconos(btn_icono_ganador20);        
        ponerLogoFinal(btn_ganastefinal);
        
        
    }
     public void ponerImagenesIconos(JButton btn_poner_iconos) {
        imagen = new ImageIcon(getClass().getResource("/Imagenes/ganador2.gif"));
        icono = new ImageIcon(imagen.getImage().getScaledInstance(btn_poner_iconos.getWidth(),
                btn_poner_iconos.getHeight(), Image.SCALE_DEFAULT));
        btn_poner_iconos.setIcon(icono);
    } 
    public void ponerLogoFinal(JButton btn_ganador_final) {
        imagen = new ImageIcon(getClass().getResource("/Imagenes/ganador1.gif"));
        icono = new ImageIcon(imagen.getImage().getScaledInstance(btn_ganador_final.getWidth(),
                btn_ganador_final.getHeight(), Image.SCALE_DEFAULT));
        btn_ganador_final.setIcon(icono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_icono_ganador18 = new javax.swing.JButton();
        btn_icono_ganador4 = new javax.swing.JButton();
        btn_icono_ganador5 = new javax.swing.JButton();
        btn_icono_ganador7 = new javax.swing.JButton();
        btn_icono_ganador8 = new javax.swing.JButton();
        btn_icono_ganador11 = new javax.swing.JButton();
        btn_icono_ganador20 = new javax.swing.JButton();
        btn_icono_ganador19 = new javax.swing.JButton();
        btn_icono_ganador = new javax.swing.JButton();
        btn_icono_ganador2 = new javax.swing.JButton();
        btn_icono_ganador3 = new javax.swing.JButton();
        btn_icono_ganador17 = new javax.swing.JButton();
        btn_icono_ganador10 = new javax.swing.JButton();
        btn_icono_ganador16 = new javax.swing.JButton();
        btn_icono_ganador15 = new javax.swing.JButton();
        btn_icono_ganador9 = new javax.swing.JButton();
        btn_icono_ganador14 = new javax.swing.JButton();
        btn_icono_ganador13 = new javax.swing.JButton();
        btn_icono_ganador6 = new javax.swing.JButton();
        btn_icono_ganador12 = new javax.swing.JButton();
        btn_ganastefinal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(177, 60, 31));
        setMinimumSize(new java.awt.Dimension(460, 420));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        btn_icono_ganador18.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.add(btn_icono_ganador18);
        btn_icono_ganador18.setBounds(20, 200, 60, 50);

        btn_icono_ganador4.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.add(btn_icono_ganador4);
        btn_icono_ganador4.setBounds(230, 20, 60, 50);

        btn_icono_ganador5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(btn_icono_ganador5);
        btn_icono_ganador5.setBounds(300, 20, 60, 50);

        btn_icono_ganador7.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.add(btn_icono_ganador7);
        btn_icono_ganador7.setBounds(370, 80, 60, 50);

        btn_icono_ganador8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(btn_icono_ganador8);
        btn_icono_ganador8.setBounds(370, 140, 60, 50);

        btn_icono_ganador11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(btn_icono_ganador11);
        btn_icono_ganador11.setBounds(370, 320, 60, 50);

        btn_icono_ganador20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(btn_icono_ganador20);
        btn_icono_ganador20.setBounds(20, 80, 60, 50);

        btn_icono_ganador19.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.add(btn_icono_ganador19);
        btn_icono_ganador19.setBounds(20, 140, 60, 50);

        btn_icono_ganador.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.add(btn_icono_ganador);
        btn_icono_ganador.setBounds(20, 20, 60, 50);

        btn_icono_ganador2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(btn_icono_ganador2);
        btn_icono_ganador2.setBounds(90, 20, 60, 50);

        btn_icono_ganador3.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.add(btn_icono_ganador3);
        btn_icono_ganador3.setBounds(160, 20, 60, 50);

        btn_icono_ganador17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(btn_icono_ganador17);
        btn_icono_ganador17.setBounds(20, 260, 60, 50);

        btn_icono_ganador10.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.add(btn_icono_ganador10);
        btn_icono_ganador10.setBounds(370, 260, 60, 50);

        btn_icono_ganador16.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.add(btn_icono_ganador16);
        btn_icono_ganador16.setBounds(20, 320, 60, 50);

        btn_icono_ganador15.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.add(btn_icono_ganador15);
        btn_icono_ganador15.setBounds(90, 320, 60, 50);

        btn_icono_ganador9.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.add(btn_icono_ganador9);
        btn_icono_ganador9.setBounds(370, 200, 60, 50);

        btn_icono_ganador14.setBackground(new java.awt.Color(255, 255, 255));
        btn_icono_ganador14.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(btn_icono_ganador14);
        btn_icono_ganador14.setBounds(160, 320, 60, 50);

        btn_icono_ganador13.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.add(btn_icono_ganador13);
        btn_icono_ganador13.setBounds(230, 320, 60, 50);

        btn_icono_ganador6.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.add(btn_icono_ganador6);
        btn_icono_ganador6.setBounds(370, 20, 60, 50);

        btn_icono_ganador12.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.add(btn_icono_ganador12);
        btn_icono_ganador12.setBounds(300, 320, 60, 50);

        btn_ganastefinal.setBackground(new java.awt.Color(222, 159, 33));
        jPanel1.add(btn_ganastefinal);
        btn_ganastefinal.setBounds(100, 90, 250, 210);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconofondo.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 470, 390);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 470, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ganaste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ganaste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ganaste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ganaste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ganaste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ganastefinal;
    private javax.swing.JButton btn_icono_ganador;
    private javax.swing.JButton btn_icono_ganador10;
    private javax.swing.JButton btn_icono_ganador11;
    private javax.swing.JButton btn_icono_ganador12;
    private javax.swing.JButton btn_icono_ganador13;
    private javax.swing.JButton btn_icono_ganador14;
    private javax.swing.JButton btn_icono_ganador15;
    private javax.swing.JButton btn_icono_ganador16;
    private javax.swing.JButton btn_icono_ganador17;
    private javax.swing.JButton btn_icono_ganador18;
    private javax.swing.JButton btn_icono_ganador19;
    private javax.swing.JButton btn_icono_ganador2;
    private javax.swing.JButton btn_icono_ganador20;
    private javax.swing.JButton btn_icono_ganador3;
    private javax.swing.JButton btn_icono_ganador4;
    private javax.swing.JButton btn_icono_ganador5;
    private javax.swing.JButton btn_icono_ganador6;
    private javax.swing.JButton btn_icono_ganador7;
    private javax.swing.JButton btn_icono_ganador8;
    private javax.swing.JButton btn_icono_ganador9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
